FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY package.json ./
RUN npm install --production

COPY server.js ./

RUN mkdir -p /data/screenshots /data/archives

EXPOSE 3000

CMD ["node", "server.js"]
